export const ar = {
  welcome: "مرحبا",
  home: "الرئيسية",
  ai: "AI",
  easy: "إيزي",
  drEasy: "دكتور إيزي",
  reExamination: "إعادة الفحص",
  addPatient: "إضافة مرضى",
  followingUP: "متابعة",
  examination: "الفحص",
  allPatients: "جميع المرضى",
  live: "مباشر",
  medicalTest: "فحص طبي",
  accountReports: "تقارير الحساب",
  wall: "المنتدي",
  settings: "الإعدادات",
  changePassword: "تغيير كلمة المرور",
  changelanguage: "تغيير اللغه",
  logout: "تسجيل الخروج",
  english: "إنجليزي",
  arabic: "عربي",
  save: "حفظ",
  inputs: "المدخلات",
  expense: "المصروفات",
  netprofit: "صافي الربح",
  up: "أعلى ",
  down: "أقل ",
  fromYesterday: "من البارحه",
};
