export const en={
  welcome:'welcome',
  home:'home',
  easy:'easy',
  drEasy:'dr easy',
  reExamination: 'e-examination',
  addPatient: 'add-patients',
  followingUP: 'following up',
  examination:'examination',
  allPatients:'all patients',
  live:'live',
  medicalTest:'medical test',
  accountReports:'account reports',
  settings:'settings',
  changePassword:'change password',
  changelanguage: 'change language',
  logout:'logout',
  english:'english',
  arabic:'arabic',
  save:'save',
  inputs:'inputs',
  expense: 'expense',
  netprofit:'net profit',
  up: 'up',
  down: 'down',
  fromYesterday: 'from yesterday',
}