export interface patientFollowing {
  code: string;
  name: string;
  gender: string;
  age: number;
  examinationType: string;
  arriveStatus: boolean;
}

export const patientsFollowingList: patientFollowing[] = [
  {
    code: "P001",
    name: "John Doe",
    gender: "Male",
    age: 30,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P002",
    name: "Jane Doe",
    gender: "Female",
    age: 25,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P003",
    name: "Alex Smith",
    gender: "Male",
    age: 40,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P004",
    name: "Emily Johnson",
    gender: "Female",
    age: 28,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P005",
    name: "Michael Brown",
    gender: "Male",
    age: 35,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P006",
    name: "Sarah Lee",
    gender: "Female",
    age: 32,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P007",
    name: "William Davis",
    gender: "Male",
    age: 45,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P008",
    name: "Olivia Martin",
    gender: "Female",
    age: 29,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P009",
    name: "James Wilson",
    gender: "Male",
    age: 38,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P010",
    name: "Ava Taylor",
    gender: "Female",
    age: 26,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P011",
    name: "George Miller",
    gender: "Male",
    age: 42,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P012",
    name: "Isabella White",
    gender: "Female",
    age: 31,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P013",
    name: "Benjamin Harris",
    gender: "Male",
    age: 36,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P014",
    name: "Sophia Thompson",
    gender: "Female",
    age: 27,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P015",
    name: "Alexander Lewis",
    gender: "Male",
    age: 44,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P016",
    name: "Mia Hall",
    gender: "Female",
    age: 30,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P017",
    name: "Ethan Walker",
    gender: "Male",
    age: 39,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P018",
    name: "Charlotte Jackson",
    gender: "Female",
    age: 33,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P019",
    name: "Lucas Brooks",
    gender: "Male",
    age: 41,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P020",
    name: "Amelia Garcia",
    gender: "Female",
    age: 34,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P021",
    name: "Hannah Martin",
    gender: "Female",
    age: 24,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P022",
    name: "Logan Davis",
    gender: "Male",
    age: 43,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P023",
    name: "Gabriel Brown",
    gender: "Male",
    age: 37,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P024",
    name: "Julia Wilson",
    gender: "Female",
    age: 29,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P025",
    name: "Elijah Taylor",
    gender: "Male",
    age: 40,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P026",
    name: "Ava Lee",
    gender: "Female",
    age: 27,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P027",
    name: "William Johnson",
    gender: "Male",
    age: 45,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P028",
    name: "Sophia Harris",
    gender: "Female",
    age: 30,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P029",
    name: "Oliver White",
    gender: "Male",
    age: 38,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P030",
    name: "Mia Thompson",
    gender: "Female",
    age: 26,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P031",
    name: "Benjamin Lewis",
    gender: "Male",
    age: 42,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P032",
    name: "Isabella Hall",
    gender: "Female",
    age: 31,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P033",
    name: "Alexander Walker",
    gender: "Male",
    age: 39,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P034",
    name: "Charlotte Jackson",
    gender: "Female",
    age: 33,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P035",
    name: "Lucas Brooks",
    gender: "Male",
    age: 41,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P036",
    name: "Amelia Garcia",
    gender: "Female",
    age: 34,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P037",
    name: "Hannah Martin",
    gender: "Female",
    age: 24,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P038",
    name: "Logan Davis",
    gender: "Male",
    age: 43,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P039",
    name: "Gabriel Brown",
    gender: "Male",
    age: 37,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P040",
    name: "Julia Wilson",
    gender: "Female",
    age: 29,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P041",
    name: "Elijah Taylor",
    gender: "Male",
    age: 40,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P042",
    name: "Ava Lee",
    gender: "Female",
    age: 27,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P043",
    name: "William Johnson",
    gender: "Male",
    age: 45,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P044",
    name: "Sophia Harris",
    gender: "Female",
    age: 30,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P045",
    name: "Oliver White",
    gender: "Male",
    age: 38,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P046",
    name: "Mia Thompson",
    gender: "Female",
    age: 26,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P047",
    name: "Benjamin Lewis",
    gender: "Male",
    age: 42,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P048",
    name: "Isabella Hall",
    gender: "Female",
    age: 31,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P049",
    name: "Alexander Walker",
    gender: "Male",
    age: 39,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P050",
    name: "Charlotte Jackson",
    gender: "Female",
    age: 33,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P051",
    name: "Lucas Brooks",
    gender: "Male",
    age: 41,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P052",
    name: "Amelia Garcia",
    gender: "Female",
    age: 34,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P053",
    name: "Hannah Martin",
    gender: "Female",
    age: 24,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P054",
    name: "Logan Davis",
    gender: "Male",
    age: 43,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P055",
    name: "Gabriel Brown",
    gender: "Male",
    age: 37,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P056",
    name: "Julia Wilson",
    gender: "Female",
    age: 29,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P057",
    name: "Elijah Taylor",
    gender: "Male",
    age: 40,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P058",
    name: "Ava Lee",
    gender: "Female",
    age: 27,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P059",
    name: "William Johnson",
    gender: "Male",
    age: 45,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P060",
    name: "Sophia Harris",
    gender: "Female",
    age: 30,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P061",
    name: "Oliver White",
    gender: "Male",
    age: 38,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P062",
    name: "Mia Thompson",
    gender: "Female",
    age: 26,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P063",
    name: "Benjamin Lewis",
    gender: "Male",
    age: 42,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P064",
    name: "Isabella Hall",
    gender: "Female",
    age: 31,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P065",
    name: "Alexander Walker",
    gender: "Male",
    age: 39,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P066",
    name: "Charlotte Jackson",
    gender: "Female",
    age: 33,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P067",
    name: "Lucas Brooks",
    gender: "Male",
    age: 41,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P068",
    name: "Amelia Garcia",
    gender: "Female",
    age: 34,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P069",
    name: "Hannah Martin",
    gender: "Female",
    age: 24,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P070",
    name: "Logan Davis",
    gender: "Male",
    age: 43,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P071",
    name: "Gabriel Brown",
    gender: "Male",
    age: 37,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P072",
    name: "Julia Wilson",
    gender: "Female",
    age: 29,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P073",
    name: "Elijah Taylor",
    gender: "Male",
    age: 40,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P074",
    name: "Ava Lee",
    gender: "Female",
    age: 27,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P075",
    name: "William Johnson",
    gender: "Male",
    age: 45,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P076",
    name: "Sophia Harris",
    gender: "Female",
    age: 30,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P077",
    name: "Oliver White",
    gender: "Male",
    age: 38,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P078",
    name: "Mia Thompson",
    gender: "Female",
    age: 26,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P079",
    name: "Benjamin Lewis",
    gender: "Male",
    age: 42,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P080",
    name: "Isabella Hall",
    gender: "Female",
    age: 31,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P081",
    name: "Alexander Walker",
    gender: "Male",
    age: 39,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P082",
    name: "Charlotte Jackson",
    gender: "Female",
    age: 33,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P083",
    name: "Lucas Brooks",
    gender: "Male",
    age: 41,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P084",
    name: "Amelia Garcia",
    gender: "Female",
    age: 34,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P085",
    name: "Hannah Martin",
    gender: "Female",
    age: 24,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P086",
    name: "Logan Davis",
    gender: "Male",
    age: 43,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P087",
    name: "Gabriel Brown",
    gender: "Male",
    age: 37,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P088",
    name: "Julia Wilson",
    gender: "Female",
    age: 29,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P089",
    name: "Elijah Taylor",
    gender: "Male",
    age: 40,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P090",
    name: "Ava Lee",
    gender: "Female",
    age: 27,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P091",
    name: "William Johnson",
    gender: "Male",
    age: 45,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P092",
    name: "Sophia Harris",
    gender: "Female",
    age: 30,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P093",
    name: "Oliver White",
    gender: "Male",
    age: 38,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P094",
    name: "Mia Thompson",
    gender: "Female",
    age: 26,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P095",
    name: "Benjamin Lewis",
    gender: "Male",
    age: 42,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P096",
    name: "Isabella Hall",
    gender: "Female",
    age: 31,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P097",
    name: "Alexander Walker",
    gender: "Male",
    age: 39,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P098",
    name: "Charlotte Jackson",
    gender: "Female",
    age: 33,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P099",
    name: "Lucas Brooks",
    gender: "Male",
    age: 41,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P100",
    name: "Amelia Garcia",
    gender: "Female",
    age: 34,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P101",
    name: "Ethan Thompson",
    gender: "Male",
    age: 35,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P102",
    name: "Ava Lee",
    gender: "Female",
    age: 29,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P103",
    name: "Liam Patel",
    gender: "Male",
    age: 38,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P104",
    name: "Sophia Martin",
    gender: "Female",
    age: 32,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P105",
    name: "Noah Harris",
    gender: "Male",
    age: 40,
    examinationType: "New",
    arriveStatus: false,
  },
  {
    code: "P106",
    name: "Mia Davis",
    gender: "Female",
    age: 36,
    examinationType: "Resumption",
    arriveStatus: true,
  },
  {
    code: "P107",
    name: "Elijah Taylor",
    gender: "Male",
    age: 37,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P108",
    name: "Isabella White",
    gender: "Female",
    age: 30,
    examinationType: "Resumption",
    arriveStatus: false,
  },
  {
    code: "P109",
    name: "William Brown",
    gender: "Male",
    age: 43,
    examinationType: "New",
    arriveStatus: true,
  },
  {
    code: "P110",
    name: "Olivia Johnson",
    gender: "Female",
    age: 35,
    examinationType: "Resumption",
    arriveStatus: true,
  },
];
