export interface medicine{
  name: string,
  dose:string,
  time:string,
  note?:string
}

export interface medicalFile{
  name: string,
  file:any,
  note?:string,
  date?:Date
}

export const Medicines:string[] = [
  "Acetaminophen", "Ibuprofen", "Aspirin", "Amoxicillin", "Lisinopril",
  "Metformin", "Omeprazole", "Levothyroxine", "Amlodipine", "Metoprolol",
  "Sertraline", "Gabapentin", "Losartan", "Atorvastatin", "Escitalopram",
  "Azithromycin", "Albuterol", "Hydrochlorothiazide", "Prednisone", "Fluoxetine",
  "Pantoprazole", "Furosemide", "Citalopram", "Tramadol", "Montelukast",
  "Cetirizine", "Trazodone", "Cyclobenzaprine", "Carvedilol", "Duloxetine",
  "Meloxicam", "Bupropion", "Clonazepam", "Clopidogrel", "Venlafaxine",
  "Warfarin", "Rosuvastatin", "Hydroxyzine", "Doxycycline", "Alprazolam",
  "Diazepam", "Lorazepam", "Naproxen", "Simvastatin", "Fluticasone",
  "Ranitidine", "Paroxetine", "Methylprednisolone", "Famotidine", "Ciprofloxacin",
  "Cephalexin", "Loratadine", "Propranolol", "Dicyclomine", "Clindamycin",
  "Ondansetron", "Mirtazapine", "Spironolactone", "Buspirone", "Pravastatin",
  "Oxycodone", "Metronidazole", "Diltiazem", "Valsartan", "Topiramate",
  "Quetiapine", "Olanzapine", "Risperidone", "Lamotrigine", "Levetiracetam",
  "Glipizide", "Promethazine", "Amitriptyline", "Atenolol", "Clonidine",
  "Digoxin", "Doxazosin", "Estradiol", "Fenofibrate", "Glimepiride",
  "Hydralazine", "Hydroxychloroquine", "Isosorbide", "Ketoconazole", "Labetalol",
  "Methocarbamol", "Nifedipine", "Nitrofurantoin", "Nortriptyline", "Oxcarbazepine",
  "Penicillin", "Phenytoin", "Pioglitazone", "Ramipril", "Rifampin",
  "Sotalol", "Sulfamethoxazole", "Tamsulosin", "Terazosin", "Tetracycline",
  "Timolol", "Tolterodine", "Triamterene", "Valacyclovir", "Zolpidem",
  "Acarbose", "Acebutolol", "Acetazolamide", "Acyclovir", "Adapalene",
  "Adenosine", "Albendazole", "Allopurinol", "Amantadine", "Amiodarone",
  "Amlodipine-Benazepril", "Amoxicillin-Clavulanate", "Ampicillin", "Anastrozole", "Apixaban",
  "Aripiprazole", "Atovaquone", "Baclofen", "Benazepril", "Bendroflumethiazide",
  "Betamethasone", "Betaxolol", "Bisacodyl", "Bismuth", "Brimonidine",
  "Budesonide", "Buprenorphine", "Butalbital", "Calcitriol", "Candesartan",
  "Captopril", "Carbidopa", "Carisoprodol", "Carbamazepine", "Carboplatin",
  "Cefadroxil", "Cefdinir", "Cefixime", "Cefpodoxime", "Ceftriaxone",
  "Celecoxib", "Cevimeline", "Chlorthalidone", "Chlorzoxazone", "Cilostazol",
  "Cinacalcet", "Clarithromycin", "Clobetasol", "Clomipramine", "Clotrimazole",
  "Colchicine", "Conjugated Estrogens", "Cortisone", "Cyanocobalamin", "Cyclophosphamide",
  "Dabigatran", "Dapsone", "Darifenacin", "Desvenlafaxine", "Dexamethasone",
  "Dexlansoprazole", "Dextroamphetamine", "Diclofenac", "Didanosine", "Diflunisal",
  "Digitoxin", "Diloxanide", "Diphenhydramine", "Dipyridamole", "Disopyramide",
  "Dofetilide", "Donepezil", "Dorzolamide", "Doxepin", "Dronabinol",
  "Dronedarone", "Dutasteride", "Econazole", "Efavirenz", "Enalapril",
  "Enoxaparin", "Entacapone", "Epinephrine", "Eprosartan", "Ergocalciferol",
  "Erythromycin", "Escitalopram", "Esomeprazole", "Estazolam", "Ethambutol",
  "Ethinyl Estradiol", "Etidronate", "Etoposide", "Etravirine", "Exemestane",
  "Ezetimibe", "Famciclovir", "Felodipine", "Fentanyl", "Fexofenadine",
  "Finasteride", "Flavoxate", "Flecainide", "Fluconazole", "Fludrocortisone",
  "Flumazenil", "Fluorouracil", "Fluphenazine", "Flurbiprofen", "Fluvastatin",
  "Fluvoxamine", "Folic Acid", "Fosinopril", "Frovatriptan", "Fulvestrant",
  "Furosemide", "Gabapentin", "Galantamine", "Ganciclovir", "Gefitinib",
  "Gemfibrozil", "Gentamicin", "Glatiramer", "Glimepiride", "Glipizide",
  "Glucagon", "Glyburide", "Glycopyrrolate", "Granisetron", "Guaifenesin",
  "Guanfacine", "Haloperidol", "Heparin", "Hydrocortisone", "Hydromorphone",
  "Hydroxyzine", "Ibandronate", "Imatinib", "Imipenem", "Imipramine",
  "Indapamide", "Indomethacin", "Insulin", "Irbesartan", "Irinotecan",
  "Isoniazid", "Isosorbide", "Isotretinoin", "Itraconazole", "Ivermectin",
  "Ketamine", "Ketorolac", "Lacosamide", "Lactulose", "Lamivudine",
  "Lansoprazole", "Latanoprost", "Leflunomide", "Letrozole", "Leucovorin",
  "Leuprolide", "Levobunolol", "Levocetirizine", "Levodopa", "Levofloxacin"
]